/*
** EPITECH PROJECT, 2021
** strace
** File description:
** syscalls table
*/

#ifndef SYSCALL_H_
    #define SYSCALL_H_

    #include <stdio.h>
    #include <stdlib.h>
    #include <unistd.h>
    #include <sys/ptrace.h>
    #include <sys/wait.h>
    #include <sys/user.h>
    #include <fcntl.h>
    #include <string.h>
    #include <stdbool.h>

    #ifndef _GNU_SOURCE
        #define _GNU_SOURCE
    #endif

    #ifdef EXIT_FAILURE
        #undef EXIT_FAILURE
        #define EXIT_FAILURE 84
    #endif

    #define NUM 1
    #define STRING 2
    #define UNS 3
    #define VOID_P (4)
    #define CST_VOID_P (5)
    #define ST_P (7)
    #define ST_STAT_P (8)
    #define ST_FD_P (9)
    #define PVOID (12)
    #define CST_KERNEL_SIGSET_T_P (13)
    #define KERNEL_SIGSET_T_P (14)
    #define VARGS (16)
    #define CST_ST_IOVEC_P (17)
    #define FD_SET_P (18)
    #define ST_TIMEVAL_P (19)
    #define VOID (20)
    #define ST_SHMID_DS_P (23)
    #define CST_ST_TIMESPEC_P (24)
    #define ST_TIMESPEC_P (25)
    #define ST_ITIMERVAL_P (26)
    #define CST_ST_ITIMERVAL_P (28)
    #define CST_ST_SOCKADDR_P (31)
    #define SOCKLEN_T (32)
    #define ST_SOCKADDR_P (33)
    #define SOCKLEN_T_P (34)
    #define CST_ST_MSGHDR_P (35)
    #define ST_MSGHDR_P (36)
    #define ST_RUSAGE_P (39)
    #define ST_UTSNAME_P (40)
    #define ST_SEMBUF_P (41)
    #define ST_MSQID_DS_P (43)
    #define ST_LINUX_DIRENT_P (44)
    #define MODE_T (49)
    #define UID_T (51)
    #define GID_T (52)
    #define ST_TIMEZONE_P (53)
    #define ST_RLIMIT_P (54)
    #define CLOCK_T (55)
    #define ST_TMS_P (56)
    #define ENUM_____REQUEST (57)
    #define CST_GID_T_P (58)
    #define UID_T_P (59)
    #define GID_T_P (60)
    #define CAP_USER_HEADER_T (61)
    #define CAP_USER_DATA_T (62)
    #define CST_CAP_USER_DATA_T (63)
    #define CST_STACK_T_P (64)
    #define STACK_T_P (65)
    #define CST_ST_UTIMBUF_P (66)
    #define DEV_T (67)
    #define ST_STATFS_P (68)
    #define ID_T (69)
    #define CST_ST_SCHED_PARAM_P (70)
    #define ST_SCHED_PARAM_P (71)
    #define ST_TIMESPEC_P_ (72)
    #define ST____ARGS_P (73)
    #define ST_TIMEX_P (74)
    #define CST_ST_RLIMIT_P (75)
    #define CST_ST_TIMEVAL_P (76)
    #define CST_ST_TIMEZONE_P (77)
    #define CADDR_T (78)
    #define ST_KERNEL_SYM_P (79)
    #define NUM_P (80)
    #define ST_NFSCTL_ARG_P (81)
    #define UNION_NFSCTL_RES_P (82)
    #define OFF64_T (83)
    #define TIME_T (84)
    #define _T___T_P (85)
    #define CST_CPU_SET_T_P (86)
    #define CPU_SET_T_P (87)
    #define ST_USER_DESC_P (88)
    #define AIO_CONTEXT_T_P (90)
    #define AIO_CONTEXT_T (91)
    #define ST_IO_EVENT_P (92)
    #define ST_IOCB_P (93)
    #define U64 (94)
    #define ST_LINUX_DIRENT64_P (95)
    #define CLOCKID_T (96)
    #define ST_SIGEVENT_P (97)
    #define TIMER_T_P (98)
    #define TIMER_T (99)
    #define CST_ST_ITIMERSPEC_P (100)
    #define ST_ITIMERSPEC_P (101)
    #define ST_EPOLL_EVENT_P (102)
    #define CST_ST_TIMEVAL (103)
    #define CST_UNS_P (104)
    #define UNS_P (105)
    #define MQD_T (106)
    #define CST_ST_SIGEVENT_P (108)
    #define ST_MQ_ATTR_P (109)
    #define ST_KEXEC_SEGMENT_P (110)
    #define IDTYPE_T (111)
    #define SIGINFO_T_P (112)
    #define KEY_SERIAL_T (113)
    #define UNUM32_T (114)
    #define ST_POLLFD_P (115)
    #define CST_SIGSET_T_P (116)
    #define ST_ROBUST_LIST_HEAD_P (117)
    #define LNUM_P (118)
    #define CST_NUM_P (119)
    #define CST_ST_TIMESPEC (120)
    #define ST_PERF_EVENT_ATTR_P (121)
    #define ST_MMSGHDR_P (122)
    #define UNUM64_T (123)
    #define ST_FILE_HANDLE_P (124)
    #define ST__CACHE_P (126)
    #define ST_SCHED_ATTR_P (127)
    #define UNION__ATTR_P (128)

typedef struct {
    size_t rdi;
    size_t rsi;
    size_t rdx;
    size_t rcx;
    size_t r8;
    size_t r9;
    size_t orig_rax;
    size_t rax;
} registers_t;

typedef struct syscall_s {
    short index;
    char *syscall_name;
    short argument_count;
    int args[7];
    void (*fn)(registers_t *regs, const pid_t *pid);
} syscall_t;

void handle_unk_syscall(registers_t *regs, const pid_t *pid);
void handle_write_syscall(registers_t *regs, const pid_t *pid);
void handle_open_syscall(registers_t *regs, const pid_t *pid);
void handle_openat_syscall(registers_t *regs, const pid_t *pid);
void handle_open_syscall(registers_t *regs, const pid_t *pid);

typedef struct {
    int flag;
    const char *name;
} flag_info_t;

static const syscall_t table[336] = {
    {0, "read", 3, {NUM, NUM, VOID_P, NUM, 0, 0, 0}, handle_write_syscall},
    {1, "write", 3, {NUM, NUM, STRING, NUM, 0, 0, 0}, handle_write_syscall},
    {2, "open", 2, {NUM, STRING, NUM, 0, 0, 0, 0}, handle_open_syscall},
    {3, "close", 1, {NUM, NUM, 0, 0, 0, 0, 0}, handle_unk_syscall},
    {4, "stat", 2, {NUM, STRING, ST_STAT_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {5, "fstat", 2, {NUM, NUM, ST_STAT_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {6, "lstat", 2, {NUM, STRING, ST_STAT_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {7, "poll", 3, {NUM, ST_FD_P, UNS, NUM, 0, 0, 0},
        handle_unk_syscall},
    {8, "lseek", 3, {NUM, NUM, NUM, NUM, 0, 0, 0},
        handle_unk_syscall},
    {9, "mmap", 6, {PVOID, VOID_P, NUM, NUM, NUM, NUM, NUM},
        handle_unk_syscall},
    {10, "mprotect", 3, {NUM, VOID_P, NUM, NUM, 0, 0, 0},
        handle_unk_syscall},
    {11, "munmap", 2, {NUM, VOID_P, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {12, "brk", 1, {NUM, VOID_P, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {13, "rt_sigaction", 6, {0, 0, 0, 0, 0, 0, 0}, handle_unk_syscall},
    {14, "rt_sigprocmask", 4,
        {NUM, NUM, CST_KERNEL_SIGSET_T_P, KERNEL_SIGSET_T_P, NUM, 0, 0},
        handle_unk_syscall},
    {15, "rt_sigreturn", 6, {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {16, "ioctl", 3, {NUM, NUM, UNS, VARGS, 0, 0, 0},
        handle_unk_syscall},
    {17, "pread64", 6, {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {18, "pwrite64", 6, {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {19, "readv", 3, {NUM, NUM, CST_ST_IOVEC_P, NUM, 0, 0, 0},
        handle_unk_syscall},
    {20, "writev", 3, {NUM, NUM, CST_ST_IOVEC_P, NUM, 0, 0, 0},
        handle_unk_syscall},
    {21, "access", 2, {NUM, STRING, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {22, "pipe", 1, {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {23, "select", 5,
        {NUM, NUM, FD_SET_P, FD_SET_P, FD_SET_P, ST_TIMEVAL_P, 0},
        handle_unk_syscall},
    {24, "sched_yield", 1,
        {NUM, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {25, "mremap", 0, {PVOID, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {26, "msync", 3, {NUM, VOID_P, NUM, NUM, 0, 0, 0},
        handle_unk_syscall},
    {27, "mincore", 3, {NUM, VOID_P, NUM, STRING, 0, 0, 0},
        handle_unk_syscall},
    {28, "madvise", 3, {NUM, VOID_P, NUM, NUM, 0, 0, 0},
        handle_unk_syscall},
    {29, "shmget", 3, {NUM, NUM, NUM, NUM, 0, 0, 0},
        handle_unk_syscall},
    {30, "shmat", 3, {PVOID, NUM, CST_VOID_P, NUM, 0, 0, 0},
        handle_unk_syscall},
    {31, "shmctl", 3, {NUM, NUM, NUM, ST_SHMID_DS_P, 0, 0, 0},
        handle_unk_syscall},
    {32, "dup", 1, {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {33, "dup2", 2, {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {34, "pause", 1, {NUM, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {35, "nanosleep", 2,
        {NUM, CST_ST_TIMESPEC_P, ST_TIMESPEC_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {36, "getitimer", 2,
        {NUM, NUM, ST_ITIMERVAL_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {37, "alarm", 1,
        {UNS, UNS, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {38, "setitimer", 3,
        {NUM, NUM, CST_ST_ITIMERVAL_P, ST_ITIMERVAL_P, 0, 0, 0},
        handle_unk_syscall},
    {39, "getpid", 1,
        {NUM, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {40, "sendfile", 4,
        {NUM, NUM, NUM, NUM_P, NUM, 0, 0},
        handle_unk_syscall},
    {41, "socket", 3,
        {NUM, NUM, NUM, NUM, 0, 0, 0},
        handle_unk_syscall},
    {42, "connect", 3,
        {NUM, NUM, CST_ST_SOCKADDR_P, SOCKLEN_T, 0, 0, 0},
        handle_unk_syscall},
    {43, "accept", 3,
        {NUM, NUM, ST_SOCKADDR_P, SOCKLEN_T_P, 0, 0, 0},
        handle_unk_syscall},
    {44, "sendto", 6,
        {NUM, NUM, CST_VOID_P, NUM, NUM, CST_ST_SOCKADDR_P, SOCKLEN_T},
        handle_unk_syscall},
    {45, "recvfrom", 6,
        {NUM, NUM, VOID_P, NUM, NUM, ST_SOCKADDR_P, SOCKLEN_T_P},
        handle_unk_syscall},
    {46, "sendmsg", 3,
        {NUM, NUM, CST_ST_MSGHDR_P, NUM, 0, 0, 0},
        handle_unk_syscall},
    {47, "recvmsg", 3,
        {NUM, NUM, ST_MSGHDR_P, NUM, 0, 0, 0},
        handle_unk_syscall},
    {48, "shutdown", 2,
        {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {49, "bind", 3,
        {NUM, NUM, CST_ST_SOCKADDR_P, SOCKLEN_T, 0, 0, 0},
        handle_unk_syscall},
    {50, "listen", 2,
        {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {51, "getsockname", 3,
        {NUM, NUM, ST_SOCKADDR_P, SOCKLEN_T_P, 0, 0, 0},
        handle_unk_syscall},
    {52, "getpeername", 3,
        {NUM, NUM, ST_SOCKADDR_P, SOCKLEN_T_P, 0, 0, 0},
        handle_unk_syscall},
    {53, "socketpair", 4,
        {NUM, NUM, NUM, NUM, NUM, 0, 0},
        handle_unk_syscall},
    {54, "setsockopt", 5,
        {NUM, NUM, NUM, NUM, CST_VOID_P, SOCKLEN_T, 0},
        handle_unk_syscall},
    {55, "getsockopt", 5,
        {NUM, NUM, NUM, NUM, VOID_P, SOCKLEN_T_P, 0},
        handle_unk_syscall},
    {56, "clone", 0,
        {NUM, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {57, "fork", 1,
        {NUM, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {58, "vfork", 1,
        {NUM, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {59, "execve", 3,
        {NUM, STRING, STRING, STRING, 0, 0, 0},
        handle_unk_syscall},
    {60, "exit", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {61, "wait4", 4,
        {NUM, NUM, NUM_P, NUM, ST_RUSAGE_P, 0, 0},
        handle_unk_syscall},
    {62, "kill", 2,
        {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {63, "uname", 1,
        {NUM, ST_UTSNAME_P, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {64, "semget", 3,
        {NUM, NUM, NUM, NUM, 0, 0, 0},
        handle_unk_syscall},
    {65, "semop", 3,
        {NUM, NUM, ST_SEMBUF_P, NUM, 0, 0, 0},
        handle_unk_syscall},
    {66, "semctl", 4,
        {NUM, NUM, NUM, NUM, VARGS, 0, 0},
        handle_unk_syscall},
    {67, "shmdt", 1,
        {NUM, CST_VOID_P, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {68, "msgget", 2,
        {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {69, "msgsnd", 4,
        {NUM, NUM, CST_VOID_P, NUM, NUM, 0, 0},
        handle_unk_syscall},
    {70, "msgrcv", 5,
        {NUM, NUM, VOID_P, NUM, NUM, NUM, 0},
        handle_unk_syscall},
    {71, "msgctl", 3,
        {NUM, NUM, NUM, ST_MSQID_DS_P, 0, 0, 0},
        handle_unk_syscall},
    {72, "fcntl", 0,
        {NUM, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {73, "flock", 2,
        {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {74, "fsync", 1,
        {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {75, "fdatasync", 1,
        {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {76, "truncate", 2,
        {NUM, STRING, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {77, "ftruncate", 2,
        {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {78, "getdents", 3,
        {NUM, UNS, ST_LINUX_DIRENT_P, UNS, 0, 0, 0},
        handle_unk_syscall},
    {79, "getcwd", 2,
        {NUM, STRING, UNS, 0, 0, 0, 0},
        handle_unk_syscall},
    {80, "chdir", 1,
        {NUM, STRING, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {81, "fchdir", 1,
        {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {82, "rename", 2,
        {NUM, STRING, STRING, 0, 0, 0, 0},
        handle_unk_syscall},
    {83, "mkdir", 2,
        {NUM, STRING, MODE_T, 0, 0, 0, 0},
        handle_unk_syscall},
    {84, "rmdir", 1,
        {NUM, STRING, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {85, "creat", 2,
        {NUM, STRING, MODE_T, 0, 0, 0, 0},
        handle_unk_syscall},
    {86, "link", 2,
        {NUM, STRING, STRING, 0, 0, 0, 0},
        handle_unk_syscall},
    {87, "unlink", 1,
        {NUM, STRING, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {88, "symlink", 2,
        {NUM, STRING, STRING, 0, 0, 0, 0},
        handle_unk_syscall},
    {89, "readlink", 3,
        {NUM, STRING, STRING, NUM, 0, 0, 0},
        handle_unk_syscall},
    {90, "chmod", 2,
        {NUM, STRING, MODE_T, 0, 0, 0, 0},
        handle_unk_syscall},
    {91, "fchmod", 2,
        {NUM, NUM, MODE_T, 0, 0, 0, 0},
        handle_unk_syscall},
    {92, "chown", 3,
        {NUM, STRING, UID_T, GID_T, 0, 0, 0},
        handle_unk_syscall},
    {93, "fchown", 3,
        {NUM, NUM, UID_T, GID_T, 0, 0, 0},
        handle_unk_syscall},
    {94, "lchown", 3,
        {NUM, STRING, UID_T, GID_T, 0, 0, 0},
        handle_unk_syscall},
    {95, "umask", 1,
        {MODE_T, MODE_T, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {96, "gettimeofday", 2,
        {NUM, ST_TIMEVAL_P, ST_TIMEZONE_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {97, "getrlimit", 2,
        {NUM, NUM, ST_RLIMIT_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {98, "getrusage", 2,
        {NUM, NUM, ST_RUSAGE_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {99, "sysinfo", 1,
        {NUM, ST_P, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {100, "times", 1,
        {CLOCK_T, ST_TMS_P, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {101, "ptrace", 4,
        {NUM, ENUM_____REQUEST, NUM, VOID_P, VOID_P, 0, 0},
        handle_unk_syscall},
    {102, "getuid", 1,
        {UID_T, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {103, "syslog", 3,
        {NUM, NUM, STRING, NUM, 0, 0, 0},
        handle_unk_syscall},
    {104, "getgid", 1,
        {GID_T, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {105, "setuid", 1,
        {NUM, UID_T, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {106, "setgid", 1,
        {NUM, GID_T, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {107, "geteuid", 1,
        {UID_T, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {108, "getegid", 1,
        {GID_T, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {109, "setpgid", 2,
        {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {110, "getppid", 1,
        {NUM, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {111, "getpgrp", 0,
        {NUM, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {112, "setsid", 1,
        {NUM, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {113, "setreuid", 2,
        {NUM, UID_T, UID_T, 0, 0, 0, 0},
        handle_unk_syscall},
    {114, "setregid", 2,
        {NUM, GID_T, GID_T, 0, 0, 0, 0},
        handle_unk_syscall},
    {115, "getgroups", 2,
        {NUM, NUM, GID_T, 0, 0, 0, 0},
        handle_unk_syscall},
    {116, "setgroups", 2,
        {NUM, NUM, CST_GID_T_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {117, "setresuid", 3,
        {NUM, UID_T, UID_T, UID_T, 0, 0, 0},
        handle_unk_syscall},
    {118, "getresuid", 3,
        {NUM, UID_T_P, UID_T_P, UID_T_P, 0, 0, 0},
        handle_unk_syscall},
    {119, "setresgid", 3,
        {NUM, GID_T, GID_T, GID_T, 0, 0, 0},
        handle_unk_syscall},
    {120, "getresgid", 3,
        {NUM, GID_T_P, GID_T_P, GID_T_P, 0, 0, 0},
        handle_unk_syscall},
    {121, "getpgid", 1,
        {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {122, "setfsuid", 1,
        {NUM, UID_T, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {123, "setfsgid", 1,
        {NUM, UID_T, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {124, "getsid", 1,
        {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {125, "capget", 2,
        {NUM, CAP_USER_HEADER_T, CAP_USER_DATA_T, 0, 0, 0, 0},
        handle_unk_syscall},
    {126, "capset", 2,
        {NUM, CAP_USER_HEADER_T, CST_CAP_USER_DATA_T, 0, 0, 0, 0},
        handle_unk_syscall},
    {127, "rt_sigpending", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {128, "rt_sigtimedwait", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {129, "rt_sigqueueinfo", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {130, "rt_sigsuspend", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {131, "sigaltstack", 2,
        {NUM, CST_STACK_T_P, STACK_T_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {132, "utime", 2,
        {NUM, STRING, CST_ST_UTIMBUF_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {133, "mknod", 3,
        {NUM, STRING, MODE_T, DEV_T, 0, 0, 0},
        handle_unk_syscall},
    {134, "uselib", 1,
        {NUM, STRING, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {135, "personality", 1,
        {NUM, UNS, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {136, "ustat", 2,
        {NUM, DEV_T, ST_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {137, "statfs", 2,
        {NUM, STRING, ST_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {138, "fstatfs", 2,
        {NUM, NUM, ST_STATFS_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {139, "sysfs", 2,
        {NUM, NUM, STRING, 0, 0, 0, 0},
        handle_unk_syscall},
    {140, "getpriority", 2,
        {NUM, NUM, ID_T, 0, 0, 0, 0},
        handle_unk_syscall},
    {141, "setpriority", 3,
        {NUM, NUM, ID_T, NUM, 0, 0, 0},
        handle_unk_syscall},
    {142, "sched_setparam", 2,
        {NUM, NUM, CST_ST_SCHED_PARAM_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {143, "sched_getparam", 2,
        {NUM, NUM, ST_SCHED_PARAM_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {144, "sched_setscheduler", 3,
        {NUM, NUM, NUM, CST_ST_SCHED_PARAM_P, 0, 0, 0},
        handle_unk_syscall},
    {145, "sched_getscheduler", 1, {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {146, "sched_get_priority_max", 1, {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {147, "sched_get_priority_min", 1, {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {148, "sched_rr_get_interval", 2,
        {NUM, NUM, ST_TIMESPEC_P_, 0, 0, 0, 0},
        handle_unk_syscall},
    {149, "mlock", 2,
        {NUM, CST_VOID_P, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {150, "munlock", 2,
        {NUM, CST_VOID_P, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {151, "mlockall", 1,
        {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {152, "munlockall", 1,
        {NUM, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {153, "vhangup", 1,
        {NUM, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {154, "modify_ldt", 3,
        {NUM, NUM, VOID_P, UNS, 0, 0, 0},
        handle_unk_syscall},
    {155, "pivot_root", 2,
        {NUM, STRING, STRING, 0, 0, 0, 0},
        handle_unk_syscall},
    {156, "_sysctl", 1,
        {NUM, ST____ARGS_P, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {157, "prctl", 5,
        {NUM, NUM, UNS, UNS, UNS, UNS, 0},
        handle_unk_syscall},
    {158, "arch_prctl", 2,
        {NUM, NUM, UNS, 0, 0, 0, 0},
        handle_unk_syscall},
    {159, "adjtimex", 1,
        {NUM, ST_TIMEX_P, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {160, "setrlimit", 2,
        {NUM, NUM, CST_ST_RLIMIT_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {161, "chroot", 1,
        {NUM, STRING, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {162, "sync", 1,
        {VOID, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {163, "acct", 1,
        {NUM, STRING, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {164, "settimeofday", 2,
        {NUM, CST_ST_TIMEVAL_P, CST_ST_TIMEZONE_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {165, "mount", 5,
        {NUM, STRING, STRING, STRING, UNS, CST_VOID_P, 0},
        handle_unk_syscall},
    {166, "umount2", 2,
        {NUM, STRING, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {167, "swapon", 2,
        {NUM, STRING, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {168, "swapoff", 1,
        {NUM, STRING, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {169, "reboot", 4,
        {NUM, NUM, NUM, NUM, VOID_P, 0, 0},
        handle_unk_syscall},
    {170, "sethostname", 2,
        {NUM, STRING, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {171, "setdomainname", 2,
        {NUM, STRING, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {172, "iopl", 1,
        {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {173, "ioperm", 3,
        {NUM, UNS, UNS, NUM, 0, 0, 0},
        handle_unk_syscall},
    {174, "create_module", 2,
        {CADDR_T, STRING, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {175, "init_module", 3,
        {NUM, VOID_P, UNS, STRING, 0, 0, 0},
        handle_unk_syscall},
    {176, "delete_module", 2,
        {NUM, STRING, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {177, "get_kernel_syms", 1,
        {NUM, ST_KERNEL_SYM_P, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {178, "query_module", 5,
        {NUM, STRING, NUM, VOID_P, NUM, NUM_P, 0},
        handle_unk_syscall},
    {179, "quotactl", 4,
        {NUM, NUM, STRING, NUM, CADDR_T, 0, 0},
        handle_unk_syscall},
    {180, "nfsservctl", 3,
        {NUM, NUM, ST_NFSCTL_ARG_P, UNION_NFSCTL_RES_P, 0, 0, 0},
        handle_unk_syscall},
    {181, "getpmsg", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {182, "putpmsg", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {183, "afs_syscall", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {184, "tuxcall", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {185, "security", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {186, "gettid", 1,
        {NUM, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {187, "readahead", 3,
        {NUM, NUM, OFF64_T, NUM, 0, 0, 0},
        handle_unk_syscall},
    {188, "setxattr", 5,
        {NUM, STRING, STRING, CST_VOID_P, NUM, NUM, 0},
        handle_unk_syscall},
    {189, "lsetxattr", 5,
        {NUM, STRING, STRING, CST_VOID_P, NUM, NUM, 0},
        handle_unk_syscall},
    {190, "fsetxattr", 5,
        {NUM, NUM, STRING, CST_VOID_P, NUM, NUM, 0},
        handle_unk_syscall},
    {191, "getxattr", 4,
        {NUM, STRING, STRING, VOID_P, NUM, 0, 0},
        handle_unk_syscall},
    {192, "lgetxattr", 4,
        {NUM, STRING, STRING, VOID_P, NUM, 0, 0},
        handle_unk_syscall},
    {193, "fgetxattr", 4,
        {NUM, NUM, STRING, VOID_P, NUM, 0, 0},
        handle_unk_syscall},
    {194, "listxattr", 3,
        {NUM, STRING, STRING, NUM, 0, 0, 0},
        handle_unk_syscall},
    {195, "llistxattr", 3,
        {NUM, STRING, STRING, NUM, 0, 0, 0},
        handle_unk_syscall},
    {196, "flistxattr", 3,
        {NUM, NUM, STRING, NUM, 0, 0, 0},
        handle_unk_syscall},
    {197, "removexattr", 2,
        {NUM, STRING, STRING, 0, 0, 0, 0},
        handle_unk_syscall},
    {198, "lremovexattr", 2,
        {NUM, STRING, STRING, 0, 0, 0, 0},
        handle_unk_syscall},
    {199, "fremovexattr", 2,
        {NUM, NUM, STRING, 0, 0, 0, 0},
        handle_unk_syscall},
    {200, "tkill", 2,
        {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {201, "time", 1,
        {TIME_T, _T___T_P, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {202, "futex", 0,
        {NUM, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {203, "sched_setaffinity", 3,
        {NUM, NUM, NUM, CST_CPU_SET_T_P, 0, 0, 0},
        handle_unk_syscall},
    {204, "sched_getaffinity", 3,
        {NUM, NUM, NUM, CPU_SET_T_P, 0, 0, 0},
        handle_unk_syscall},
    {205, "set_thread_area", 1,
        {NUM, ST_USER_DESC_P, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {206, "io_setup", 2,
        {NUM, UNS, AIO_CONTEXT_T_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {207, "io_destroy", 1,
        {NUM, AIO_CONTEXT_T, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {208, "io_getevents", 5,
        {NUM, AIO_CONTEXT_T, NUM, NUM, ST_IO_EVENT_P, ST_TIMESPEC_P, 0},
        handle_unk_syscall},
    {209, "io_submit", 3,
        {NUM, AIO_CONTEXT_T, NUM, ST_IOCB_P, 0, 0, 0},
        handle_unk_syscall},
    {210, "io_cancel", 3,
        {NUM, AIO_CONTEXT_T, ST_IOCB_P, ST_IO_EVENT_P, 0, 0, 0},
        handle_unk_syscall},
    {211, "get_thread_area", 1,
        {NUM, ST_USER_DESC_P, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {212, "lookup_dcookie", 3,
        {NUM, U64, STRING, NUM, 0, 0, 0},
        handle_unk_syscall},
    {213, "epoll_create", 1,
        {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {214, "epoll_ctl_old", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {215, "epoll_wait_old", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {216, "remap_file_pages", 5,
        {NUM, VOID_P, NUM, NUM, NUM, NUM, 0},
        handle_unk_syscall},
    {217, "getdents64", 3,
        {NUM, UNS, ST_LINUX_DIRENT64_P, UNS, 0, 0, 0},
        handle_unk_syscall},
    {218, "set_tid_address", 1,
        {NUM, NUM_P, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {219, "restart_syscall", 1,
        {NUM, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {220, "semtimedop", 4,
        {NUM, NUM, ST_SEMBUF_P, NUM, CST_ST_TIMESPEC_P, 0, 0},
        handle_unk_syscall},
    {221, "fadvise64", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {222, "timer_create", 3,
        {NUM, CLOCKID_T, ST_SIGEVENT_P, TIMER_T_P, 0, 0, 0},
        handle_unk_syscall},
    {223, "timer_settime", 4,
        {NUM, TIMER_T, NUM, CST_ST_ITIMERSPEC_P, ST_ITIMERSPEC_P, 0, 0},
        handle_unk_syscall},
    {224, "timer_gettime", 2,
        {NUM, TIMER_T, ST_ITIMERSPEC_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {225, "timer_getoverrun", 1,
        {NUM, TIMER_T, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {226, "timer_delete", 1,
        {NUM, TIMER_T, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {227, "clock_settime", 2,
        {NUM, CLOCKID_T, CST_ST_TIMESPEC_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {228, "clock_gettime", 2,
        {NUM, CLOCKID_T, ST_TIMESPEC_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {229, "clock_getres", 2,
        {NUM, CLOCKID_T, ST_TIMESPEC_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {230, "clock_nanosleep", 4,
        {NUM, CLOCKID_T, NUM, CST_ST_TIMESPEC_P, ST_TIMESPEC_P, 0, 0},
        handle_unk_syscall},
    {231, "exit_group", 1,
        {VOID, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {232, "epoll_wait", 4,
        {NUM, NUM, ST_EPOLL_EVENT_P, NUM, NUM, 0, 0},
        handle_unk_syscall},
    {233, "epoll_ctl", 4,
        {NUM, NUM, NUM, NUM, ST_EPOLL_EVENT_P, 0, 0},
        handle_unk_syscall},
    {234, "tgkill", 3,
        {NUM, NUM, NUM, NUM, 0, 0, 0},
        handle_unk_syscall},
    {235, "utimes", 2,
        {NUM, STRING, CST_ST_TIMEVAL, 0, 0, 0, 0},
        handle_unk_syscall},
    {236, "vserver", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {237, "mbind", 6,
        {NUM, VOID_P, UNS, NUM, CST_UNS_P, UNS, UNS},
        handle_unk_syscall},
    {238, "set_mempolicy", 3,
        {NUM, NUM, CST_UNS_P, UNS, 0, 0, 0},
        handle_unk_syscall},
    {239, "get_mempolicy", 5,
        {NUM, NUM_P, UNS_P, UNS, VOID_P, UNS, 0},
        handle_unk_syscall},
    {240, "mq_open", 2,
        {MQD_T, STRING, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {241, "mq_unlink", 1,
        {NUM, STRING, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {242, "mq_timedsend", 5,
        {NUM, MQD_T, STRING, NUM, UNS, CST_ST_TIMESPEC_P, 0},
        handle_unk_syscall},
    {243, "mq_timedreceive", 5,
        {NUM, MQD_T, STRING, NUM, UNS_P, CST_ST_TIMESPEC_P, 0},
        handle_unk_syscall},
    {244, "mq_notify", 2,
        {NUM, MQD_T, CST_ST_SIGEVENT_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {245, "mq_getsetattr", 3,
        {NUM, MQD_T, ST_MQ_ATTR_P, ST_MQ_ATTR_P, 0, 0, 0},
        handle_unk_syscall},
    {246, "kexec_load", 4,
        {NUM, UNS, UNS, ST_KEXEC_SEGMENT_P, UNS, 0, 0},
        handle_unk_syscall},
    {247, "waitid", 4,
        {NUM, IDTYPE_T, ID_T, SIGINFO_T_P, NUM, 0, 0},
        handle_unk_syscall},
    {248, "add_key", 5,
        {KEY_SERIAL_T, STRING, STRING, CST_VOID_P, NUM, KEY_SERIAL_T, 0},
        handle_unk_syscall},
    {249, "request_key", 4,
        {KEY_SERIAL_T, STRING, STRING, STRING, KEY_SERIAL_T, 0, 0},
        handle_unk_syscall},
    {250, "keyctl", 2,
        {NUM, NUM, VARGS, 0, 0, 0, 0},
        handle_unk_syscall},
    {251, "ioprio_set", 3,
        {NUM, NUM, NUM, NUM, 0, 0, 0},
        handle_unk_syscall},
    {252, "ioprio_get", 2,
        {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {253, "inotify_init", 1,
        {NUM, VOID, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {254, "inotify_add_watch", 3,
        {NUM, NUM, STRING, UNUM32_T, 0, 0, 0},
        handle_unk_syscall},
    {255, "inotify_rm_watch", 2,
        {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {256, "migrate_pages", 4,
        {NUM, NUM, UNS, CST_UNS_P, CST_UNS_P, 0, 0},
        handle_unk_syscall},
    {257, "openat", 3,
        {NUM, NUM, STRING, NUM, 0, 0, 0},
        handle_openat_syscall},
    {258, "mkdirat", 3,
        {NUM, NUM, STRING, MODE_T, 0, 0, 0},
        handle_unk_syscall},
    {259, "mknodat", 4,
        {NUM, NUM, STRING, MODE_T, DEV_T, 0, 0},
        handle_unk_syscall},
    {260, "fchownat", 5,
        {NUM, NUM, STRING, UID_T, GID_T, NUM, 0},
        handle_unk_syscall},
    {261, "futimesat", 3,
        {NUM, NUM, STRING, CST_ST_TIMEVAL, 0, 0, 0},
        handle_unk_syscall},
    {262, "newfstatat", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {263, "unlinkat", 3,
        {NUM, NUM, STRING, NUM, 0, 0, 0},
        handle_unk_syscall},
    {264, "renameat", 4,
        {NUM, NUM, STRING, NUM, STRING, 0, 0},
        handle_unk_syscall},
    {265, "linkat", 5,
        {NUM, NUM, STRING, NUM, STRING, NUM, 0},
        handle_unk_syscall},
    {266, "symlinkat", 3,
        {NUM, STRING, NUM, STRING, 0, 0, 0},
        handle_unk_syscall},
    {267, "readlinkat", 4,
        {NUM, NUM, STRING, STRING, NUM, 0, 0},
        handle_unk_syscall},
    {268, "fchmodat", 4,
        {NUM, NUM, STRING, MODE_T, NUM, 0, 0},
        handle_unk_syscall},
    {269, "faccessat", 4,
        {NUM, NUM, STRING, NUM, NUM, 0, 0},
        handle_unk_syscall},
    {270, "pselect6", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {271, "ppoll", 4,
        {NUM, ST_POLLFD_P, UNS, CST_ST_TIMESPEC_P, CST_SIGSET_T_P, 0, 0},
        handle_unk_syscall},
    {272, "unshare", 1,
        {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {273, "set_robust_list", 2,
        {NUM, ST_ROBUST_LIST_HEAD_P, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {274, "get_robust_list", 3,
        {NUM, NUM, ST_ROBUST_LIST_HEAD_P, NUM_P, 0, 0, 0},
        handle_unk_syscall},
    {275, "splice", 6,
        {NUM, NUM, LNUM_P, NUM, LNUM_P, NUM, UNS},
        handle_unk_syscall},
    {276, "tee", 4,
        {NUM, NUM, NUM, NUM, UNS, 0, 0},
        handle_unk_syscall},
    {277, "sync_file_range", 4,
        {NUM, NUM, OFF64_T, OFF64_T, UNS, 0, 0},
        handle_unk_syscall},
    {278, "vmsplice", 4,
        {NUM, NUM, CST_ST_IOVEC_P, UNS, UNS, 0, 0},
        handle_unk_syscall},
    {279, "move_pages", 6,
        {NUM, NUM, UNS, VOID_P, CST_NUM_P, NUM_P, NUM},
        handle_unk_syscall},
    {280, "utimensat", 4,
        {NUM, NUM, STRING, CST_ST_TIMESPEC, NUM, 0, 0},
        handle_unk_syscall},
    {281, "epoll_pwait", 5,
        {NUM, NUM, ST_EPOLL_EVENT_P, NUM, NUM, CST_SIGSET_T_P, 0},
        handle_unk_syscall},
    {282, "signalfd", 3,
        {NUM, NUM, CST_SIGSET_T_P, NUM, 0, 0, 0},
        handle_unk_syscall},
    {283, "timerfd_create", 2,
        {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {284, "eventfd", 2,
        {NUM, UNS, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {285, "fallocate", 4,
        {NUM, NUM, NUM, NUM, NUM, 0, 0},
        handle_unk_syscall},
    {286, "timerfd_settime", 4,
        {NUM, NUM, NUM, CST_ST_ITIMERSPEC_P, ST_ITIMERSPEC_P, 0, 0},
        handle_unk_syscall},
    {287, "timerfd_gettime", 2,
        {NUM, NUM, ST_ITIMERSPEC_P, 0, 0, 0, 0},
        handle_unk_syscall},
    {288, "accept4", 4,
        {NUM, NUM, ST_SOCKADDR_P, SOCKLEN_T_P, NUM, 0, 0},
        handle_unk_syscall},
    {289, "signalfd4", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {290, "eventfd2", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {291, "epoll_create1", 1,
        {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {292, "dup3", 3,
        {NUM, NUM, NUM, NUM, 0, 0, 0},
        handle_unk_syscall},
    {293, "pipe2", 2,
        {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {294, "inotify_init1", 1,
        {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {295, "preadv", 4,
        {NUM, NUM, CST_ST_IOVEC_P, NUM, NUM, 0, 0},
        handle_unk_syscall},
    {296, "pwritev", 4,
        {NUM, NUM, CST_ST_IOVEC_P, NUM, NUM, 0, 0},
        handle_unk_syscall},
    {297, "rt_tgsigqueueinfo", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {298, "perf_event_open", 5,
        {NUM, ST_PERF_EVENT_ATTR_P, NUM, NUM, NUM, UNS, 0},
        handle_unk_syscall},
    {299, "recvmmsg", 5,
        {NUM, NUM, ST_MMSGHDR_P, UNS, UNS, ST_TIMESPEC_P, 0},
        handle_unk_syscall},
    {300, "fanotify_init", 2,
        {NUM, UNS, UNS, 0, 0, 0, 0},
        handle_unk_syscall},
    {301, "fanotify_mark", 5,
        {NUM, NUM, UNS, UNUM64_T, NUM, STRING, 0},
        handle_unk_syscall},
    {302, "prlimit64", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {303, "name_to_handle_at", 5,
        {NUM, NUM, STRING, ST_FILE_HANDLE_P, NUM_P, NUM, 0},
        handle_unk_syscall},
    {304, "open_by_handle_at", 3,
        {NUM, NUM, ST_FILE_HANDLE_P, NUM, 0, 0, 0},
        handle_unk_syscall},
    {305, "clock_adjtime", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {306, "syncfs", 1,
        {NUM, NUM, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {307, "sendmmsg", 4,
        {NUM, NUM, ST_MMSGHDR_P, UNS, UNS, 0, 0},
        handle_unk_syscall},
    {308, "setns", 2,
        {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {309, "getcpu", 3,
        {NUM, UNS_P, UNS_P, ST__CACHE_P, 0, 0, 0},
        handle_unk_syscall},
    {310, "process_vm_readv", 6,
        {NUM, NUM, CST_ST_IOVEC_P, UNS, CST_ST_IOVEC_P, UNS, UNS},
        handle_unk_syscall},
    {311, "process_vm_writev", 6,
        {NUM, NUM, CST_ST_IOVEC_P, UNS, CST_ST_IOVEC_P, UNS, UNS},
        handle_unk_syscall},
    {312, "kcmp", 5,
        {NUM, NUM, NUM, NUM, UNS, UNS, 0},
        handle_unk_syscall},
    {313, "finit_module", 3,
        {NUM, NUM, STRING, NUM, 0, 0, 0},
        handle_unk_syscall},
    {314, "sched_setattr", 3,
        {NUM, NUM, ST_SCHED_ATTR_P, UNS, 0, 0, 0},
        handle_unk_syscall},
    {315, "sched_getattr", 4,
        {NUM, NUM, ST_SCHED_ATTR_P, UNS, UNS, 0, 0},
        handle_unk_syscall},
    {316, "renameat2", 5,
        {NUM, NUM, STRING, NUM, STRING, UNS, 0},
        handle_unk_syscall},
    {317, "seccomp", 3,
        {NUM, UNS, UNS, VOID_P, 0, 0, 0},
        handle_unk_syscall},
    {318, "getrandom", 3,
        {NUM, VOID_P, NUM, UNS, 0, 0, 0},
        handle_unk_syscall},
    {319, "memfd_create", 2,
        {NUM, STRING, UNS, 0, 0, 0, 0},
        handle_unk_syscall},
    {320, "kexec_file_load", 5,
        {NUM, NUM, NUM, UNS, STRING, UNS, 0},
        handle_unk_syscall},
    {321, "bpf", 3,
        {NUM, NUM, UNION__ATTR_P, UNS, 0, 0, 0},
        handle_unk_syscall},
    {322, "execveat", 5,
        {NUM, NUM, STRING, STRING, STRING, NUM, 0},
        handle_unk_syscall},
    {323, "userfaultfd", 6,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {324, "membarrier", 2,
        {NUM, NUM, NUM, 0, 0, 0, 0},
        handle_unk_syscall},
    {325, "mlock2", 3,
        {NUM, CST_VOID_P, NUM, NUM, 0, 0, 0},
        handle_unk_syscall},
    {326, "copy_file_range", 6,
        {NUM, NUM, LNUM_P, NUM, LNUM_P, NUM, UNS},
        handle_unk_syscall},
    {327, "preadv2", 5,
        {NUM, NUM, CST_ST_IOVEC_P, NUM, NUM, NUM, 0},
        handle_unk_syscall},
    {328, "pwritev2", 5,
        {NUM, NUM, CST_ST_IOVEC_P, NUM, NUM, NUM, 0},
        handle_unk_syscall},
    {329, NULL, 0,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {330, NULL, 0,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {331, NULL, 0,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {332, NULL, 0,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {333, NULL, 0,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
    {334, "rseq", 4,
        {NUM, VOID_P, VOID_P, NUM, VOID_P, 0, 0},
        handle_unk_syscall},
    {335, NULL, 0,
        {0, 0, 0, 0, 0, 0, 0},
        handle_unk_syscall},
};

#endif
